export {websites}

const websites = [
    {
      name: "OfZenAndComputing.com",
      type: "Content", 
      monetization: "Affiliate Sales",
      netProfitPerMonth: 4823, 
      price: 153000,
      description: "Passive & Growing 4yr old Tech & Gaming Blog with High DA & Extensive Opportunities for Growth, Generating $5,864/m in Net Profit w/ Diversified Income Streams",
      img: "https://d2jafhvbn4akdi.cloudfront.net/webp_c6f5edd0-5809-43bd-9ad6-807ad5c2f4ef.png",
    },
    {
      name: "sitea.net & zynken.com",
      type: "SaaS", 
      monetization: "Other",
      netProfitPerMonth: 38, 
      price: 99,
      description: "Discover brandable domains, with high DA, PA and domain authority. Ready for a thriving business no required for coding knowledge. Don't miss the Opportunity!",
      img: "https://d2jafhvbn4akdi.cloudfront.net/026c1b1b-2c80-475e-8431-9ed7c9f73a56.jpg",
  
    },
    {
      name: "Salvatore Tripi eBay & Etsy Store",
      type: "Ecommerce", 
      monetization: "Ecommerce",
      netProfitPerMonth: 6153, 
      price: 115691,
      description: "A business website operating in the UK, focusing on providing services like coaching, training, and mentoring using proven methodologies.",
      img: "https://d2jafhvbn4akdi.cloudfront.net/0cd73853-9c19-4624-bebd-5d248b6f223c.png",
    },
    {
      name: "TapGifty - Real Cash Rewards",
      type: "SaaS", 
      monetization: "Affiliate Sales",
      netProfitPerMonth: 964, 
      price: 23049,
      description: "TapGifty - Cash Rewards a business that operates by offering a gift service, providing users with a convenient way to send personalized and thoughtful gifts.",
      img: "https://d2jafhvbn4akdi.cloudfront.net/f70e6a6f-36cd-442a-8590-6c877aa8e737.png",
    },
    {
      name: "Bestdroidplayer",
      type: "Content", 
      monetization: "Affiliate Sales",
      netProfitPerMonth: 3267, 
      price: 117500,
      description: "Profitable 8-Year-Old Streaming Blog with Strong Online Presence, Expertly Monetizing through VPN Affiliates.",
      img: "https://d2jafhvbn4akdi.cloudfront.net/aa2d88d8-7c97-41dc-8cf6-d9c0028ab671.png",
    },
    {
      name: "Lunar Calendar",
      type: "Content", 
      monetization: "Ads",
      netProfitPerMonth: 6196, 
      price: 250000,
      description: "The best lunar Calendar site an Ezoic VIP partner. $7589 avg. net income, 1000+ top keywords, 4M monthly users. Diverse revenue, low costs, 8+ years of success.",
      img: "https://d2jafhvbn4akdi.cloudfront.net/20d47434-0fa2-4f12-88dc-32f5f4f21437.PNG",
    },
    {
      name: "Spiel Times",
      type: "Content", 
      monetization: "Ads",
      netProfitPerMonth: 6251, 
      price: 100000,
      description: "Established in 2015, this profitable Entertainment business boasts impressive revenue and profit margins, making it a valuable opportunity for investors.",
      img: "https://d2jafhvbn4akdi.cloudfront.net/9030c1ff-ca20-428b-9393-0d5b671cf129.png",
    },
    {
      name: "Return of the Cafe Racers",
      type: "Content", 
      monetization: "Affiliate Sales",
      netProfitPerMonth: 1383, 
      price: 57770,
      description: "A 15 year old content site devoted to custom motorcycles, specifically the cafe racer. Huge social following, big and active e-mail subscriber list.",
      img: "https://d2jafhvbn4akdi.cloudfront.net/ac581c21-7fc5-4910-8306-3aa80e9a0e42.png",
    },
    {
      name: "MyPCOSKitchen",
      type: "Content", 
      monetization: "Affiliate Sales",
      netProfitPerMonth: 1576, 
      price: 53995,
      description: "MyPCOSKitchen is an 8-year-old, high-authority (57 DA) content website. This is a recipe & niche diet website making $1,600 per month. Top Quality Site!",
      img: "https://d2jafhvbn4akdi.cloudfront.net/8e9bf2ae-9ba8-4431-bf29-e3d3ddeaf0dc.png",
    },
    {
      name: "NealFun.org",
      type: "Content", 
      monetization: "Ads",
      netProfitPerMonth: 1386, 
      price: 63000,
      description: "Young Fun, Interactive Games site with 450+ Posts with Huge Gaming Opportunity, Generating $3,157.73 in Net Profit from Display Ads Only.",
      img: "https://d2jafhvbn4akdi.cloudfront.net/128a41fa-8e2e-45f8-99d0-a752706be9ce.png",
    },
    
  ]